### ISSUE TITLE
how do i build it?

### ISSUE THREAD

**Issue by PedroxTheBest99** [TheMrIron2/DeSmuME-PSP#12]
well, i want to get a up-to-date experience on this emulator, but the only compiled release has 50 commits, the source has 72 commits, so i will not get the same experience, so i want to ask, how do i build the source code? thanks ^^

- Pedrox

**Comment by IridescentRose** [comment]
This is not yet publicly available.

**Comment by IridescentRose** [comment]
@PedroxTheBest99 Builds are now available on /build/ which should have an EBOOT inside. As such, this issue is satisfied.
