### ISSUE TITLE
Where is the eboot.pbp?

### ISSUE THREAD

**Issue by zheive** [TheMrIron2/DeSmuME-PSP#17]
Hello,

Can you reupload the eboot file?

**Comment by ptnnx** [comment]
> Hello,
> 
> Can you reupload the eboot file?

Here
https://cdn.discordapp.com/attachments/828190231378919424/833853665441742908/EBOOT.PBP
Make inside `Roms` folder.

**Comment by qamichelemassa5859** [comment]
[this one compile now](https://github.com/qamichelemassa5859/DeSmuME-PSP)
